"""Collcecion.user_id and article_id to be indexed

Revision ID: 36716e4edd9f
Revises: e8169c977231
Create Date: 2024-11-14 22:21:36.717275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36716e4edd9f'
down_revision: Union[str, None] = 'e8169c977231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collections_article_id'), 'collections', ['article_id'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_article_id'), table_name='collections')
    # ### end Alembic commands ###
