"""revise article table create_at

Revision ID: 6db567f48d36
Revises: 7790d78d3577
Create Date: 2024-10-03 20:14:29.461928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db567f48d36'
down_revision: Union[str, None] = '7790d78d3577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
