"""revise article table

Revision ID: 7790d78d3577
Revises: 4ed062d52ee8
Create Date: 2024-10-03 20:13:19.274965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7790d78d3577'
down_revision: Union[str, None] = '4ed062d52ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('engagement', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('public', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('regulation', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('innovation', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('deals', sa.String(), nullable=True))
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('articles', 'deals')
    op.drop_column('articles', 'innovation')
    op.drop_column('articles', 'regulation')
    op.drop_column('articles', 'public')
    op.drop_column('articles', 'engagement')
    # ### end Alembic commands ###
