"""remove salt from User

Revision ID: bf3109a4c9eb
Revises: f816ef67fc27
Create Date: 2024-12-08 14:22:49.132097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf3109a4c9eb'
down_revision: Union[str, None] = 'f816ef67fc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_table('news_vector_table',
    sa.Column('langchain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('langchain_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('langchain_id', name='news_vector_table_pkey')
    )
    # ### end Alembic commands ###
