"""revise User id

Revision ID: f8549126643f
Revises: 1a8e8906fa43
Create Date: 2024-11-12 13:18:22.076613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8549126643f'
down_revision: Union[str, None] = '1a8e8906fa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rss_users_user_id_fkey', 'rss_users', type_='foreignkey')
    op.alter_column('rss_users', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # 重新建立外鍵約束
    op.create_foreign_key(
        'rss_users_user_id_fkey', 'rss_users', 'users', 
        ['user_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rss_users_user_id_fkey', 'rss_users', type_='foreignkey')
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('rss_users', 'user_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # 重新建立原來的外鍵約束
    op.create_foreign_key(
        'rss_users_user_id_fkey', 'rss_users', 'users', 
        ['user_id'], ['id']
    )
    # ### end Alembic commands ###
